name: Multi-Platform Build

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This defines the three different operating systems to run on
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up C++ Environment
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: GCRecompiler (Windows)
        if: runner.os == 'Windows'
        run: g++ main.cpp -o gcrecomp_windows.exe

      - name: GCRecompiler (Linux)
        if: runner.os == 'Linux'
        run: g++ main.cpp -o gcrecomp_linux

      - name: GCRecompiler (macOS)
        if: runner.os == 'macOS'
        # To make a universal binary on macOS:
        run: |
          clang++ -arch x86_64 -arch arm64 main.cpp -o gcrecomp_mac_universal

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: |
            gcrecomp_windows.exe
            gcrecomp_linux
            gcrecomp_mac_universal